name       : python-jinja
version    : 2.8
release    : 2
source     :
    - https://github.com/pallets/jinja/archive/2.8.tar.gz : e270c55a2736f39eee67daba60be64fe0790ccdbbc47cdcc3ebda3017981081f
license    : BSD-3-Clause
component  : programming.python
summary    : Jinja2 is a template engine written in pure Python.
description: |
    Jinja2 is a template engine written in pure Python.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-markupsafe
build      : |
    %python_setup
install    : |
    %python_install
