name       : python-jinja
version    : 2.10.3
release    : 11
source     :
    - https://github.com/pallets/jinja/archive/2.10.3.tar.gz : db49236731373e4f3118af880eb91bb0aa6978bc0cf8b35760f6a026f1a9ffc4
license    : BSD-3-Clause
component  : programming.python
summary    : Jinja2 is a template engine written in pure Python.
description: |
    Jinja2 is a template engine written in pure Python.
builddeps  :
    - pkgconfig(python3)
    - python-markupsafe
    - python-pytest
    - python-setuptools
rundeps    :
    - python-babel
    - python-markupsafe
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test pytest
    %python3_test pytest3
