name       : python-jinja
version    : '2.10'
release    : 6
source     :
    - https://github.com/pallets/jinja/archive/2.10.tar.gz : 0d31d3466c313a9ca014a2d904fed18cdac873a5ba1f7b70b8fd8b206cd860d6
license    : BSD-3-Clause
component  : programming.python
summary    : Jinja2 is a template engine written in pure Python.
description: |
    Jinja2 is a template engine written in pure Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-babel
    - python-markupsafe
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
