name       : python-jinja
version    : 3.1.2
release    : 14
source     :
    - https://github.com/pallets/jinja/archive/refs/tags/3.1.2.tar.gz : ecae76cd1a064d40eb46c5375f07953d747f4d65b68cd3fa5f02c91714b799fc
homepage   : https://palletsprojects.com/p/jinja/
license    : BSD-3-Clause
component  : programming.python
summary    : Jinja2 is a template engine written in pure Python.
description: |
    Jinja2 is a template engine written in pure Python.
builddeps  :
    - python-markupsafe # check
    - python-pytest     # check
rundeps    :
    - python-babel
    - python-markupsafe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
