name       : python-jinja
version    : 2.10.1
release    : 7
source     :
    - https://github.com/pallets/jinja/archive/2.10.1.tar.gz : e9baab084b8d84b511c75aca98bba8585041dbe971d5476ee53d9c6eea1b58b3
license    : BSD-3-Clause
component  : programming.python
summary    : Jinja2 is a template engine written in pure Python.
description: |
    Jinja2 is a template engine written in pure Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-babel
    - python-markupsafe
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
