name       : python-jinja
version    : 2.9.6
release    : 4
source     :
    - https://github.com/pallets/jinja/archive/2.9.6.tar.gz : fa4b0ac374a3502d4523673cfdff7a1f6cbd533a13c8050bef6dcd9168142638
license    : BSD-3-Clause
component  : programming.python
summary    : Jinja2 is a template engine written in pure Python.
description: |
    Jinja2 is a template engine written in pure Python.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-babel
    - python-markupsafe
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
